name: GradLock
channels:
  - defaults
dependencies:
  - ca-certificates=2024.12.31=haa95532_0
  - openssl=3.0.15=h827c3e9_0
  - pip=25.0=py39haa95532_0
  - python=3.9.21=h8205438_1
  - setuptools=75.8.0=py39haa95532_0
  - sqlite=3.45.3=h2bbff1b_0
  - vc=14.42=haa95532_4
  - vs2015_runtime=14.42.34433=he0abc0d_4
  - wheel=0.45.1=py39haa95532_0
  - pip:
      - annotated-types==0.7.0
      - asttokens==3.0.0
      - charset-normalizer==3.4.1
      - click==8.1.8
      - colorama==0.4.6
      - comm==0.2.2
      - cycler==0.12.1
      - debugpy==1.8.12
      - decorator==5.1.1
      - dlib==20.0.0
      - dnnlib-util==0.3.1
      - eval-type-backport==0.2.2
      - exceptiongroup==1.2.2
      - executing==2.2.0
      - filelock==3.13.1
      - fonttools==4.56.0
      - fsspec==2024.6.1
      - gdown==5.2.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - imageio==2.37.0
      - imageio-ffmpeg==0.4.3
      - importlib-metadata==8.6.1
      - ipykernel==6.29.5
      - ipython==8.18.1
      - jedi==0.19.2
      - joblib==1.4.2
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - kiwisolver==1.4.7
      - kornia==0.8.1
      - kornia-rs==0.1.9
      - lazy-loader==0.4
      - lightning-utilities==0.13.1
      - llvmlite==0.43.0
      - lpips==0.1.4
      - matplotlib-inline==0.1.7
      - mpmath==1.3.0
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - ninja==1.11.1.4
      - numba==0.60.0
      - numpy==1.26.3
      - opencv-python==4.11.0.86
      - packaging==24.2
      - pandas==2.2.3
      - parso==0.8.4
      - pillow==11.0.0
      - piq==0.8.0
      - platformdirs==4.3.6
      - prompt-toolkit==3.0.50
      - protobuf==6.31.1
      - psutil==7.0.0
      - pure-eval==0.2.3
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pygments==2.19.1
      - pyparsing==3.2.1
      - pysocks==1.7.1
      - pyspng==0.1.3
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pywavelets==1.6.0
      - pywin32==308
      - pyyaml==6.0.2
      - pyzmq==26.2.1
      - requests==2.32.3
      - scikit-dimension==0.3.4
      - scikit-image==0.24.0
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - sentry-sdk==2.33.2
      - six==1.17.0
      - smmap==5.0.2
      - soupsieve==2.6
      - stack-data==0.6.3
      - sympy==1.13.1
      - threadpoolctl==3.5.0
      - tifffile==2024.8.30
      - torch-fidelity==0.3.0
      - torchmetrics==1.6.2
      - tornado==6.4.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - triton-windows==3.2.0.post19
      - typing-extensions==4.12.2
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - wandb==0.21.0
      - wcwidth==0.2.13
      - xxhash==3.5.0
      - zipp==3.21.0
      - torch==2.6.0
      - torchvision==0.21.0
      - torchaudio==2.6.0